name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python3 -m pip install tox poetry
      - name: Run linters
        run: tox -e lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: python -m pip install tox poetry
      - name: Run tests
        run: tox -e unit
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          channel: 1.23/stable
      - name: Install dependencies
        run: python -m pip install tox poetry
      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: sg microk8s -c "tox -e integration -- --model testing"
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          # TEMPLATE-TODO: Replace the application name
          app: operator-template
          model: testing
